import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Components/Common/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`"scrollbar-thin bg-neutrals-900 text-neutrals-50 antialiased selection:bg-primary selection:text-neutrals-50"${inter.className}`}  >
        {children}  
      <Header />
      <slot />
       </body>
    </html>
  )
}
