import { Inter } from 'next/font/google'
import './globals.css'
import './global.scss'

import { neutralsNine, neutralsZ, primary } from '@/Assets/Const/ColorConst'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`scrollbar-thin bg-${neutralsNine} text-${neutralsZ} antialiased selection:${primary} selection:text-${neutralsZ}`}  >
        {children}  
       </body>
    </html>
  )
}
